/**
 * Pull request content generation. Shared by the fix-verification handler
 * (PR opened after the reporter confirms) and the triage handler (PR opened
 * directly when auto-pr-on-fix is enabled).
 *
 * These functions only generate the PR title and body — the caller is
 * responsible for actually creating the PR via github.ts.
 */

import type { FlueSession } from '@flue/runtime';
import * as v from 'valibot';
import type { IssueDetails } from './github.ts';

export interface PRContent {
	title: string;
	body: string;
}

export const prContentSchema = v.object({
	title: v.pipe(v.string(), v.description('The PR title, concise and reviewer-friendly')),
	body: v.pipe(v.string(), v.description('The full PR body in markdown')),
});

export interface PRGenerationOpts {
	issueNumber: number;
	issueDetails: IssueDetails;
	branch: string;
	/**
	 * The reporter who confirmed the fix works, when the PR follows the
	 * confirmation flow. Omitted when triage opens the PR directly.
	 */
	confirmedBy?: string | null;
}

/**
 * Generate PR title and body using the project's PR writer skill.
 */
async function generatePRWithSkill(
	session: FlueSession,
	skillName: string,
	opts: PRGenerationOpts,
): Promise<PRContent> {
	const provenance = opts.confirmedBy
		? `This PR was auto-generated by the triage bot after the reporter confirmed the fix works.
The fix branch is "${opts.branch}" targeting "main".
The issue reporter (@${opts.confirmedBy}) confirmed the fix resolves their issue.`
		: `This PR was auto-generated by the triage bot after it found and verified a fix.
The fix branch is "${opts.branch}" targeting "main".`;

	const { data } = await session.skill(skillName, {
		args: {
			issueNumber: opts.issueNumber,
			issueDetails: opts.issueDetails,
			branch: opts.branch,
			context: `${provenance}
Generate a PR title and body following your project's conventions.
The PR should reference the issue with "Closes #${opts.issueNumber}".
Do NOT create the PR yourself — just return the title and body content.`,
		},
		result: prContentSchema,
	});
	return data;
}

/**
 * Generate PR title and body using a built-in prompt (no skill required).
 */
async function generatePRWithPrompt(
	session: FlueSession,
	opts: PRGenerationOpts,
): Promise<PRContent> {
	const provenance = opts.confirmedBy
		? `- The issue reporter (@${opts.confirmedBy}) confirmed the fix resolves their issue`
		: `- The triage bot found and verified this fix automatically`;

	const { data } = await session.prompt(
		`Generate a pull request title and body for the following fix.

## Issue
**#${opts.issueNumber}: ${opts.issueDetails.title}**

${opts.issueDetails.body}

## Context
- Fix branch: \`${opts.branch}\` targeting \`main\`
${provenance}
- This PR was auto-generated by a triage bot

## Instructions
- Write a concise, descriptive PR title (not a commit message — no "fix:" prefix)
- Write a PR body that briefly explains what the fix does and why
- Include "Closes #${opts.issueNumber}" in the body
- Keep it short and useful for reviewers`,
		{ result: prContentSchema },
	);
	return data;
}

/**
 * Generate PR content using the project's PR writer skill when configured,
 * otherwise fall back to a built-in prompt.
 */
export async function generatePRContent(
	session: FlueSession,
	opts: PRGenerationOpts,
	cfg: { prSkill: string | null; prSkillName: string },
): Promise<PRContent> {
	return cfg.prSkill
		? generatePRWithSkill(session, cfg.prSkillName, opts)
		: generatePRWithPrompt(session, opts);
}
